Models/ErrorViewModel.cs
using System;

namespace StarWarsInfo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Film.cs
using System;
using System.Collections.Generic;

namespace StarWarsInfo.Models
{
    public class Film
    {
        public string Title { get; set; }
        public int Episode_id { get; set; }
        public string Opening_crawl { get; set; }
        public string Director { get; set; }
        public string Producer { get; set; }
        public DateTime Release_date { get; set; }
        public List<string> Species { get; set; }
        public List<string> Starships { get; set; }
        public List<string> Vehicles { get; set; }
        public List<string> Characters { get; set; }
        public List<string> Planets { get; set; }
        public string Url { get; set; }
        public string Created { get; set; }
        public string Edited { get; set; }
    }
}

Models/Planet.cs
using System.Collections.Generic;

namespace starWarsInfo.Models
{
    public class Planet
    {
        public string Name { get; set; }
        public string Diameter { get; set; }
        public string Rotation_period { get; set; }
        public string Orbital_period { get; set; }
        public string Gravity { get; set; }
        public string Population { get; set; }
        public string Climate { get; set; }
        public string Terrain { get; set; }
        public string Surface_water { get; set; }
        public List<string> Residents { get; set; }
        public List<string> Films { get; set; }
        public string Url { get; set; }
        public string Created { get; set; }
        public string Edited { get; set; }
    }
}

Models/Resident.cs
using System.Collections.Generic;

namespace StarWarsInfo.Models
{
    public class Resident
    {
   
        public string Name { get ; set ; }
        public string Birth_year { get ; set ; }
        public string Eye_color { get ; set ; }
        public string Gender { get ; set ; }
        public string Hair_color { get; set ; }
        public string Height { get ; set ; }
        public string Mass { get ; set ; }
        public string Skin_color { get ; set ; }
        public string Homeworld { get ; set ; }
        public List<string> Films { get ; set ; }
        public List<string> Species { get ; set ; }
        public List<string> Starships { get ; set ; }
        public List<string> Vehicles { get ; set ; }
        public string Url { get ; set ; }
        public string Created { get ; set ; }
        public string Edited { get ; set ; }
       
    }
}

Controllers/PlanetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Net.Http.Headers;
using StarWarsInfo.Models;
using starWarsInfo.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;


namespace starWarsInfo.Controllers
{
    public class PlanetController : Controller
    {
       
        private readonly IHttpClientFactory _httpClientFactory;
       
        public PlanetController(IHttpClientFactory httpClientFactory)
        {
           _httpClientFactory = httpClientFactory;
        }

        public async Task<ViewResult> GetPlanet(int id )
        {
            Planet planet   = null;
            var httpRequest  = new HttpRequestMessage(HttpMethod.Get, $"http://swapi.dev/api/planets/{id}/");
            var httpClient   = _httpClientFactory.CreateClient();
            var httpResponse = await httpClient.SendAsync(httpRequest);

            if (httpResponse.IsSuccessStatusCode)
            {
                planet = await httpResponse.Content.ReadFromJsonAsync<Planet>();
            }
            return View("Index", planet);
        }
        
       
    }
}

Views/Planet/Index.cshtml
@model starWarsInfo.Models.Planet

 <head>
    <title>"Planet :)"</title>
</head>

<body>
    <h1>@ViewBag.Header</h1>
     
    <div>        PlanetName : @Model.Name    </div>
    <div>        Diameter : @Model.Diameter    </div>
    <div>        Gravity : @Model.Gravity    </div>
    <div>        Climate : @Model.Climate    </div>
    <div>        Created : @Model.Created    </div>
    <div>        Edited : @Model.Edited    </div>
    <div>        Population : @Model.Population    </div>
    <div>        Rotation_period : @Model.Rotation_period    </div>
    <div>        Surface_water : @Model.Surface_water    </div>
    <div>        Terrain : @Model.Terrain    </div>
    <div>        URL : @Model.Url    </div>
<div>
        <h1>Residents</h1> 
       <resident-info my-elements="Model.Residents"></resident-info>
    </div>

     <div>
       <h1>Films </h1> 
         <film-info my-elements="Model.Films"></film-info>
     </div>

     <form>
        <button class="btn btn-primary" asp-action="GetPlanet" asp-controller="Planet" asp-route-id="2">Get Second Planet</button>
    </form>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StarWars</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Planet" asp-action="GetPlanet">StarWars</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="GetPlanet">Планета</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>